adjective = input('Please enter an adjective: ')
noun = input('Please enter a noun: ')
verb = input('Please enter a verb ending in -ed: ')
animal = input('Please enter an animal: ')
print('Your MadLib:')
print('THE', adjective, noun, verb, 'OVER THE LAZY BLACK', animal + '.')
